### ISSUE TITLE
Wrong Move 😂

### ISSUE THREAD

**Issue by dekrypted** [ChironSS/fentany-grabber#1]
Bad Idea :P

**Comment by ChironSS** [comment]
the only bad thing is skidding it for no reason but i dont see any reason for that since you tried to cap 1000x times like i dont know anything

**Comment by dekrypted** [comment]
You don't know anything 😂 
I didn't do shit, maybe don't leak it to Mxty and be an overall bitch

**Comment by ChironSS** [comment]
already leaked
